### ISSUE TITLE
Published or Referable source for wordlists

### ISSUE THREAD

**Issue by ArsalanRaza** [tlkh/text-emotion-classification#2]
I wanted to give a suggestion.
Kindly add Referable sources of "words-big.txt", "20k.txt" in /wordlists
I want to cite these in research. 
Thanks and Best Regards

**Comment by tlkh** [comment]
Hi. 20k.txt is from Google's 20k words corpus: https://github.com/first20hours/google-10000-english
I cannot recall the source of words-big.txt as of now.

**Comment by ArsalanRaza** [comment]
@tlkh Okay. Thank you. 👍
